In [6]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [7]:
%pip install mlflow dagshub

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.14.0)
Requirement already satisfied: dagshub in /usr/local/lib/python3.12/dist-packages (0.7.1)
Requirement already satisfied: mlflow-skinny==3.14.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.0)
Requirement already satisfied: mlflow-tracing==3.14.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.0)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.5)
Requirement already satisfied: cryptography<49,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (48.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<27 in /usr/local/lib/python3.12/dist-packages (from mlflow) (26.0.0)
Requirement already satisfied: huey<4,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.2.1)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.51)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.121.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.139.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.51)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.51.0)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.12/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.43.51)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.1.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.3)
Requirement already satisfied: botocore<1.44.0,>=1.43.51 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.43.51)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.19.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.14.0->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.14.0->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (2.46.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.4.9)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.6.4)

In [8]:
import dagshub
dagshub.init(repo_owner='xlrboi', repo_name='delievery_time_prediction', mlflow=True)

Initialized MLflow to track repo "xlrboi/delievery_time_prediction"

Repository xlrboi/delievery_time_prediction initialized!

In [5]:
import mlflow

In [9]:
mlflow.set_tracking_uri("https://dagshub.com/xlrboi/delievery_time_prediction.mlflow")

In [10]:
mlflow.set_experiment("3 - XGB HP Tuning")

<Experiment: artifact_location='mlflow-artifacts:/0df824ba0f2f4b7db389de7417d05eeb', creation_time=1784396704636, effective_trace_archival_retention=None, experiment_id='3', last_update_time=1784396704636, lifecycle_stage='active', name='3 - XGB HP Tuning', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [11]:
from sklearn import set_config

set_config(transform_output="pandas")

In [12]:
df = pd.read_csv('cleaned_data.csv')
df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37690,35.0,4.2,windy,jam,2,drinks,motorcycle,1.0,no,metropolitian,33,0,10.0,night,16.600272,very_long
37691,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
37692,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
37693,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
37694,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [13]:
temp_df = df.copy().dropna()

In [14]:
X = temp_df.drop(columns='time_taken')
y = temp_df['time_taken']

X

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37690,35.0,4.2,windy,jam,2,drinks,motorcycle,1.0,no,metropolitian,0,10.0,night,16.600272,very_long
37691,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,0,10.0,morning,1.489846,short
37692,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,0,15.0,night,4.657195,short
37693,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,0,5.0,afternoon,6.232393,medium
37694,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,0,5.0,afternoon,12.074396,long

In [15]:
y

0        24
1        33
2        26
3        21
4        30
         ..
37690    33
37691    32
37692    16
37693    26
37694    36
Name: time_taken, Length: 37695, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print("The size of train data is",X_train.shape)
print("The shape of test data is",X_test.shape)

The size of train data is (30156, 15)
The shape of test data is (7539, 15)

In [18]:
pt = PowerTransformer()

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

In [19]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [20]:
nominal_cat_cols

['weather',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_type',
 'is_weekend',
 'order_time_of_day']

In [21]:
# # features to fill values with mode

# features_to_fill_mode = ['multiple_deliveries','festival','city_type']
# features_to_fill_missing = [col for col in nominal_cat_cols if col not in features_to_fill_mode]

# features_to_fill_missing

In [22]:
# # simple imputer to fill categorical vars with mode

# simple_imputer = ColumnTransformer(transformers=[
#     ("mode_imputer",SimpleImputer(strategy="most_frequent",add_indicator=True),features_to_fill_mode),
#     ("missing_imputer",SimpleImputer(strategy="constant",fill_value="missing",add_indicator=True),features_to_fill_missing)
# ],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

# simple_imputer

In [23]:
# simple_imputer.fit_transform(X_train)

In [24]:
# simple_imputer.fit_transform(X_train).isna().sum()

In [25]:
# knn imputer

# knn_imputer = KNNImputer(n_neighbors=5)

In [26]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [27]:
# unique categories the ordinal columns

for col in ordinal_cat_cols:
    print(col,X_train[col].unique())

traffic ['jam' 'medium' 'high' 'low']
distance_type ['medium' 'short' 'long' 'very_long']

In [28]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [29]:
processing_pipeline = Pipeline(steps=[
                                # ("simple_imputer",simple_imputer),
                                ("preprocess",preprocessor)
                                # ("knn_imputer",knn_imputer)
                            ])

processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 encoded_missing_value=-999,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [30]:
X_train_trans = processing_pipeline.fit_transform(X_train)
X_test_trans = processing_pipeline.transform(X_test)

In [31]:
X_train_trans

,age,ratings,pickup_time_minutes,distance,weather_fog,weather_sandstorms,weather_stormy,weather_sunny,weather_windy,type_of_order_drinks,...,city_type_semi-urban,city_type_urban,is_weekend_1,order_time_of_day_evening,order_time_of_day_morning,order_time_of_day_night,traffic,distance_type,vehicle_condition,multiple_deliveries
7204,0.473684,0.56,1.0,0.404165,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,0,2.0
20974,1.000000,0.76,0.0,0.154044,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0,1.0
28236,0.473684,0.80,0.5,0.002461,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1,0.0
21635,1.000000,0.92,1.0,0.460411,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0,1.0
30780,0.526316,0.76,0.5,0.243676,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16850,0.578947,0.92,0.5,0.451895,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,3.0,2.0,0,0.0
6265,0.052632,1.00,1.0,0.612270,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1,1.0
11284,0.526316,0.92,0.0,0.322877,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1,0.0
860,0.947368,0.96,0.5,0.004486,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0,1.0
15795,0.684211,0.96,0.0,0.481978,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,2,1.0

In [32]:
%pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.5)
Collecting colorlog (from optuna)
  Downloading colorlog-6.11.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 20.9 MB/s eta 0:00:00
Downloading colorlog-6.11.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.11.0 optuna-4.9.0

In [33]:
from xgboost import XGBRegressor
import optuna

In [35]:
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_absolute_error, r2_score
from xgboost import XGBRegressor
import optuna
import mlflow
import mlflow.sklearn

def objective(trial):
    with mlflow.start_run(nested=True):

        params = {
            "n_estimators": trial.suggest_int("n_estimators", 200, 1200),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "max_depth": trial.suggest_int("max_depth", 3, 12),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0, 5),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 10, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 10, log=True),
            "random_state": 42,
            "device": "cuda",
            "tree_method": "hist",
            "objective": "reg:squarederror",
            "eval_metric": "mae",
            "verbosity": 0,
        }

        model = TransformedTargetRegressor(
            regressor=XGBRegressor(**params),
            transformer=pt
        )

        results = cross_validate(
            estimator=model,
            X=X_train_trans,
            y=y_train,
            cv=5,
            scoring="neg_mean_absolute_error",
            return_train_score=True,
            n_jobs=1
        )

        cv_mae = -results["test_score"].mean()
        train_mae = -results["train_score"].mean()
        cv_std = results["test_score"].std()
        fit_time = results["fit_time"].mean()

        mlflow.log_params(params)
        mlflow.log_metric("cv_mae", cv_mae)
        mlflow.log_metric("train_mae", train_mae)
        mlflow.log_metric("cv_std", cv_std)
        mlflow.log_metric("fit_time", fit_time)

        return cv_mae

study = optuna.create_study(
    direction="minimize",
    sampler=optuna.samplers.TPESampler(seed=42),
    pruner=optuna.pruners.MedianPruner()
)

with mlflow.start_run(run_name="XGBoost Hyperparameter Tuning"):

    study.optimize(
        objective,
        n_trials=100,
        n_jobs=1,
        show_progress_bar=True
    )

    mlflow.log_params(study.best_params)
    mlflow.log_metric("best_cv_mae", study.best_value)

[I 2026-07-18 19:22:03,009] A new study created in memory with name: no-name-0ad02056-9798-4ffb-8e3c-d44119f51a2f

  0%|          | 0/100 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run useful-ox-722 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/15c335fb8c764c289e948e1c911a3a24
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:22:11,248] Trial 0 finished with value: 3.1753173828125 and parameters: {'n_estimators': 574, 'learning_rate': 0.2536999076681772, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.7800932022121826, 'subsample': 0.662397808134481, 'colsample_bytree': 0.6232334448672797, 'reg_alpha': 1.574189004745663, 'reg_lambda': 0.040428727350273294}. Best is trial 0 with value: 3.1753173828125.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run inquisitive-bug-907 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/6224127049c5432188d59fd77ff01d2b
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:22:30,783] Trial 1 finished with value: 3.1272661209106447 and parameters: {'n_estimators': 908, 'learning_rate': 0.010725209743171997, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.0616955533913808, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.6733618039413735, 'reg_alpha': 0.0006690421166498799, 'reg_lambda': 0.014077923139972392}. Best is trial 1 with value: 3.1272661209106447.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run luminous-gnat-747 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/4cba6aa133f7439c9ab0a88c1c27fedd
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:22:37,658] Trial 2 finished with value: 3.1045552253723145 and parameters: {'n_estimators': 632, 'learning_rate': 0.02692655251486473, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 1.4607232426760908, 'subsample': 0.7465447373174767, 'colsample_bytree': 0.7824279936868144, 'reg_alpha': 0.5141096648805742, 'reg_lambda': 0.00015777663630582464}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run industrious-cub-578 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/0ea4e9e8c9114ef19eb9a297d61a23b3
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:22:42,971] Trial 3 finished with value: 3.4735743045806884 and parameters: {'n_estimators': 714, 'learning_rate': 0.07500118950416987, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 0.8526206184364576, 'subsample': 0.6260206371941118, 'colsample_bytree': 0.9795542149013333, 'reg_alpha': 6.220025976819156, 'reg_lambda': 0.7085721663941598}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bald-grub-604 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/bac290351140465aa83303cf14a08e47
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:22:51,506] Trial 4 finished with value: 3.1463980674743652 and parameters: {'n_estimators': 504, 'learning_rate': 0.013940346079873234, 'max_depth': 9, 'min_child_weight': 5, 'gamma': 0.6101911742238941, 'subsample': 0.798070764044508, 'colsample_bytree': 0.6137554084460873, 'reg_alpha': 2.857080075040721, 'reg_lambda': 0.0003570095960030948}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run vaunted-wolf-35 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/9f47da945d2d473bbd0a959bdbcae85c
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:23:03,817] Trial 5 finished with value: 3.1132201671600344 and parameters: {'n_estimators': 863, 'learning_rate': 0.028869220380495747, 'max_depth': 8, 'min_child_weight': 6, 'gamma': 0.9242722776276352, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.9100531293444458, 'reg_alpha': 4.33504539277513, 'reg_lambda': 2.3386439256208704}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run nimble-calf-923 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e0b213c3093f4e1eb4a3c24da853c0f8
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:23:19,780] Trial 6 finished with value: 3.3481875896453857 and parameters: {'n_estimators': 798, 'learning_rate': 0.22999586428143728, 'max_depth': 3, 'min_child_weight': 2, 'gamma': 0.22613644455269033, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.7554709158757928, 'reg_alpha': 0.0004247116662617141, 'reg_lambda': 0.9384800715909529}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run agreeable-gull-671 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/b717f1089fb34571a6c1d6a876a55257
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:23:29,002] Trial 7 finished with value: 3.1996928215026856 and parameters: {'n_estimators': 557, 'learning_rate': 0.026000059117302653, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 4.010984903770199, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.43000015861626045, 'reg_lambda': 0.00015570196345516618}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run painted-ray-919 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/cbc2f0567f004ba3bc283d7dff97724c
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:23:43,786] Trial 8 finished with value: 3.2703213691711426 and parameters: {'n_estimators': 205, 'learning_rate': 0.1601531217136121, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 3.8563517334297286, 'subsample': 0.6296178606936361, 'colsample_bytree': 0.7433862914177091, 'reg_alpha': 4.956947932799954e-05, 'reg_lambda': 1.5087613675681661}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run nosy-snake-279 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/c26f9c69656b4dcfaa53f3739d56e732
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:24:07,782] Trial 9 finished with value: 3.5300385475158693 and parameters: {'n_estimators': 823, 'learning_rate': 0.030816017044468066, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 1.6259166101337352, 'subsample': 0.8918424713352255, 'colsample_bytree': 0.8550229885420852, 'reg_alpha': 2.105118051960871, 'reg_lambda': 0.0068122338968602935}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run loud-conch-859 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3cf709339b1f404eb3176215fa111b24
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:24:28,355] Trial 10 finished with value: 3.2933094978332518 and parameters: {'n_estimators': 1153, 'learning_rate': 0.07270449316754199, 'max_depth': 6, 'min_child_weight': 10, 'gamma': 2.6276372894275966, 'subsample': 0.8300832267261091, 'colsample_bytree': 0.8189071324479795, 'reg_alpha': 0.03654348920217582, 'reg_lambda': 2.0514050378220178e-05}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run ambitious-crane-984 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/bb04cb7706f942199d30e26bc000b3b6
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:24:51,821] Trial 11 finished with value: 3.1992822647094727 and parameters: {'n_estimators': 1050, 'learning_rate': 0.030369071183923263, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 2.152973074323241, 'subsample': 0.9939499850208099, 'colsample_bytree': 0.9016761976709275, 'reg_alpha': 0.04396485490329051, 'reg_lambda': 9.655204056498564}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run delicate-trout-345 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/82056a65a2c449d69b97e6663b7774fa
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:25:04,416] Trial 12 finished with value: 3.267961835861206 and parameters: {'n_estimators': 342, 'learning_rate': 0.05023091085259384, 'max_depth': 6, 'min_child_weight': 4, 'gamma': 3.033425041274395, 'subsample': 0.9625364484051517, 'colsample_bytree': 0.9087696049520285, 'reg_alpha': 0.10274359021157886, 'reg_lambda': 0.00048279165402127046}. Best is trial 2 with value: 3.1045552253723145.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run aged-moose-335 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/388d919c0029484c98af2351871c03f1
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:25:19,801] Trial 13 finished with value: 3.078782081604004 and parameters: {'n_estimators': 1009, 'learning_rate': 0.018923803763537805, 'max_depth': 12, 'min_child_weight': 3, 'gamma': 1.5781562804498361, 'subsample': 0.9046526067205888, 'colsample_bytree': 0.777808566778909, 'reg_alpha': 0.24596141156743276, 'reg_lambda': 0.07379757848965988}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run beautiful-crow-49 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/545a5af6d4f947a380a442e8b6abbe0a
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:25:31,805] Trial 14 finished with value: 3.084691047668457 and parameters: {'n_estimators': 1056, 'learning_rate': 0.017186567556125434, 'max_depth': 12, 'min_child_weight': 3, 'gamma': 1.8368944361000787, 'subsample': 0.9006453699263156, 'colsample_bytree': 0.7660826465453201, 'reg_alpha': 0.00799180072938008, 'reg_lambda': 0.1696533718370623}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run debonair-sheep-619 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/d5ac932738f2455ab4bd632672a81a7a
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:25:51,817] Trial 15 finished with value: 3.132791757583618 and parameters: {'n_estimators': 1037, 'learning_rate': 0.015652544931319436, 'max_depth': 12, 'min_child_weight': 4, 'gamma': 2.136578234101746, 'subsample': 0.9023657445091614, 'colsample_bytree': 0.7041168086195948, 'reg_alpha': 0.002510591838350827, 'reg_lambda': 0.0714779908935222}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bustling-kit-620 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/7a89d6977c6e407ea8e316aa758e8aee
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:26:04,179] Trial 16 finished with value: 3.1157923221588133 and parameters: {'n_estimators': 1179, 'learning_rate': 0.01759046636782664, 'max_depth': 11, 'min_child_weight': 3, 'gamma': 3.302996229142291, 'subsample': 0.9023984497333888, 'colsample_bytree': 0.8343449840763744, 'reg_alpha': 0.00600310502380558, 'reg_lambda': 0.14175091703339998}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bedecked-squid-263 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/2d7346f339d049e5b64d9347b7c853ec
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:26:14,278] Trial 17 finished with value: 3.1230602264404297 and parameters: {'n_estimators': 988, 'learning_rate': 0.010160519603562351, 'max_depth': 12, 'min_child_weight': 1, 'gamma': 1.827918548631322, 'subsample': 0.8497875048310692, 'colsample_bytree': 0.6997108097658562, 'reg_alpha': 1.6513110208566485e-05, 'reg_lambda': 0.003989193622373982}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run orderly-chimp-155 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/1993ab143847415494b883222d642d98
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:26:28,602] Trial 18 finished with value: 3.112373113632202 and parameters: {'n_estimators': 980, 'learning_rate': 0.04286371592602158, 'max_depth': 11, 'min_child_weight': 3, 'gamma': 2.6127797159852633, 'subsample': 0.9354436650085622, 'colsample_bytree': 0.7892881183498337, 'reg_alpha': 0.010527606249883, 'reg_lambda': 0.19152426847188192}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run legendary-fish-606 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/a7021a67b24845d78c288c870ddfb2c2
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:26:43,820] Trial 19 finished with value: 3.0915905952453615 and parameters: {'n_estimators': 1095, 'learning_rate': 0.020184526060939338, 'max_depth': 11, 'min_child_weight': 5, 'gamma': 1.4737388135366525, 'subsample': 0.8538524221513054, 'colsample_bytree': 0.7337672369540463, 'reg_alpha': 0.15143903130351707, 'reg_lambda': 0.001676219332006909}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run chill-pig-465 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/07f56a0da6fe455eb74a8511de78dca3
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:26:52,641] Trial 20 finished with value: 3.2492040157318116 and parameters: {'n_estimators': 950, 'learning_rate': 0.047322739742887934, 'max_depth': 10, 'min_child_weight': 3, 'gamma': 4.819612188009005, 'subsample': 0.7817220916157548, 'colsample_bytree': 0.6555079757722395, 'reg_alpha': 0.0006774449917567058, 'reg_lambda': 0.02228565970170921}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run secretive-hound-423 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/48522454bae3454d848ca9392735b96f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:27:11,844] Trial 21 finished with value: 3.094288778305054 and parameters: {'n_estimators': 1069, 'learning_rate': 0.020254038400138646, 'max_depth': 11, 'min_child_weight': 5, 'gamma': 1.5035421466936447, 'subsample': 0.8734135562410865, 'colsample_bytree': 0.7249130836879707, 'reg_alpha': 0.19769491965422442, 'reg_lambda': 0.0012782795289687818}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run crawling-hound-516 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/fd123c21541b4571b29f7a0d8e907418
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:27:28,668] Trial 22 finished with value: 3.093124771118164 and parameters: {'n_estimators': 1096, 'learning_rate': 0.02036128455820631, 'max_depth': 12, 'min_child_weight': 5, 'gamma': 2.1635310533286782, 'subsample': 0.9404052868155786, 'colsample_bytree': 0.786169799770249, 'reg_alpha': 0.019616969346247865, 'reg_lambda': 0.31199273221184853}. Best is trial 13 with value: 3.078782081604004.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run agreeable-toad-140 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/7b6bee25c08c49399f55468fc32c54d9
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:27:46,596] Trial 23 finished with value: 3.053984451293945 and parameters: {'n_estimators': 1177, 'learning_rate': 0.013451944277346133, 'max_depth': 11, 'min_child_weight': 4, 'gamma': 0.18442296871633457, 'subsample': 0.8315706239555679, 'colsample_bytree': 0.765836702637975, 'reg_alpha': 0.1912024073177846, 'reg_lambda': 0.0015330771499622513}. Best is trial 23 with value: 3.053984451293945.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run agreeable-steed-245 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/cfa45d7ad3654264b6a00d54a3d03f26
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:28:08,846] Trial 24 finished with value: 3.0390724658966066 and parameters: {'n_estimators': 1184, 'learning_rate': 0.013223235775888407, 'max_depth': 12, 'min_child_weight': 3, 'gamma': 0.12716006852017758, 'subsample': 0.8033426160080553, 'colsample_bytree': 0.8541911797005439, 'reg_alpha': 0.8805110897627326, 'reg_lambda': 1.8417683635099403e-05}. Best is trial 24 with value: 3.0390724658966066.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run capable-finch-368 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3a268b9957284152bd940d0fd2e94ffb
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:28:28,577] Trial 25 finished with value: 3.0405343532562257 and parameters: {'n_estimators': 1200, 'learning_rate': 0.012442071372447377, 'max_depth': 10, 'min_child_weight': 4, 'gamma': 0.12364261857866013, 'subsample': 0.8186469962099867, 'colsample_bytree': 0.8173989282656268, 'reg_alpha': 0.9365492622492962, 'reg_lambda': 1.0673738473976083e-05}. Best is trial 24 with value: 3.0390724658966066.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bright-sponge-314 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/40656b8b42564a508cf75ac0c3499869
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:28:45,862] Trial 26 finished with value: 3.0439932346343994 and parameters: {'n_estimators': 1189, 'learning_rate': 0.012967157125781455, 'max_depth': 9, 'min_child_weight': 6, 'gamma': 0.14382018476077488, 'subsample': 0.8041723581006375, 'colsample_bytree': 0.8729094004599434, 'reg_alpha': 0.9085375326485748, 'reg_lambda': 1.3594792558119945e-05}. Best is trial 24 with value: 3.0390724658966066.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run rebellious-whale-115 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/87f61aeecdd74d00a67ca8edcd18c3d0
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:29:11,131] Trial 27 finished with value: 3.06375412940979 and parameters: {'n_estimators': 1197, 'learning_rate': 0.012302867454302244, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.0018122917779517245, 'subsample': 0.7826061310221137, 'colsample_bytree': 0.8725824140137469, 'reg_alpha': 0.9976758282127892, 'reg_lambda': 1.1023742043830912e-05}. Best is trial 24 with value: 3.0390724658966066.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run colorful-snail-499 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/414f4508303e4dbc9ee054cb16381041
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:29:22,219] Trial 28 finished with value: 3.115811824798584 and parameters: {'n_estimators': 1131, 'learning_rate': 0.010100791287517829, 'max_depth': 8, 'min_child_weight': 6, 'gamma': 0.5115936250538602, 'subsample': 0.7321253502485369, 'colsample_bytree': 0.9385279782235928, 'reg_alpha': 7.539063034893719, 'reg_lambda': 3.7809691433924645e-05}. Best is trial 24 with value: 3.0390724658966066.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run monumental-duck-246 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/96183edda18a41308d59ca92051d7e0c
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:29:34,809] Trial 29 finished with value: 3.03589186668396 and parameters: {'n_estimators': 1195, 'learning_rate': 0.013234814663955914, 'max_depth': 10, 'min_child_weight': 7, 'gamma': 0.42991213826345687, 'subsample': 0.6957765371853208, 'colsample_bytree': 0.8219138171273255, 'reg_alpha': 1.0940337935162017, 'reg_lambda': 4.191469972814515e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run silent-horse-271 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/10981043b49f4ccebd11b7b0ba5b037d
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:29:43,872] Trial 30 finished with value: 3.044748878479004 and parameters: {'n_estimators': 1125, 'learning_rate': 0.023248327639564147, 'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.5251096675648198, 'subsample': 0.6687494468844493, 'colsample_bytree': 0.8150115971464478, 'reg_alpha': 1.5390906690945318, 'reg_lambda': 5.666045329145061e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fearless-bee-745 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/234a2c420af64f2d9425a69ad779580f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:29:56,442] Trial 31 finished with value: 3.0399850368499757 and parameters: {'n_estimators': 1197, 'learning_rate': 0.0143217446950338, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.3115965470882006, 'subsample': 0.7142025867903937, 'colsample_bytree': 0.8762102665356725, 'reg_alpha': 1.2968493664513232, 'reg_lambda': 1.0292285896860005e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run wistful-wolf-658 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/c5445686ea0e45a989c35115388fcfed
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:30:05,934] Trial 32 finished with value: 3.0566779136657716 and parameters: {'n_estimators': 1116, 'learning_rate': 0.015075233673688135, 'max_depth': 10, 'min_child_weight': 9, 'gamma': 1.1333739004257297, 'subsample': 0.7079418190027924, 'colsample_bytree': 0.8489898203696512, 'reg_alpha': 0.5966049125447989, 'reg_lambda': 5.9726257993198254e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run sassy-gnu-599 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/b320c24ddf8f42d8aed25ec46cf4b483
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:30:16,921] Trial 33 finished with value: 3.1020987033843994 and parameters: {'n_estimators': 931, 'learning_rate': 0.011567633396711371, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.40820392549432893, 'subsample': 0.7016463080841943, 'colsample_bytree': 0.8168177036579253, 'reg_alpha': 9.842955994964735, 'reg_lambda': 3.0207016784714905e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run dapper-toad-301 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3d7a3786231440d398be1595fd003407
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:30:26,391] Trial 34 finished with value: 3.058715486526489 and parameters: {'n_estimators': 1195, 'learning_rate': 0.015460066708152692, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 1.1464900708153443, 'subsample': 0.7620727831014773, 'colsample_bytree': 0.950421444463226, 'reg_alpha': 0.07806930412548971, 'reg_lambda': 0.00011408040601771858}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run clumsy-trout-681 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/49e853d58f8e4505817caefc85a93aa6
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:30:39,939] Trial 35 finished with value: 3.1392210960388183 and parameters: {'n_estimators': 1120, 'learning_rate': 0.011969507886965127, 'max_depth': 7, 'min_child_weight': 8, 'gamma': 0.7300961432633021, 'subsample': 0.6918705834543013, 'colsample_bytree': 0.8838085743905432, 'reg_alpha': 3.0797263828637216, 'reg_lambda': 1.0749932488644918e-05}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run rambunctious-doe-920 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/abc4ecd8cd4c442fabc47abde220cd42
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:30:55,919] Trial 36 finished with value: 3.053467798233032 and parameters: {'n_estimators': 1026, 'learning_rate': 0.03654694663162796, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.8760367876124925, 'subsample': 0.6474335906620646, 'colsample_bytree': 0.9364368673293505, 'reg_alpha': 0.42177414572383143, 'reg_lambda': 0.00031745531476174284}. Best is trial 29 with value: 3.03589186668396.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run puzzled-gnat-412 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/b6de560100584c2b86d7f6f1a12ef710
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:31:09,367] Trial 37 finished with value: 3.0328952789306642 and parameters: {'n_estimators': 917, 'learning_rate': 0.023990844447978735, 'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.3485502356431467, 'subsample': 0.756934563125491, 'colsample_bytree': 0.8033907732881382, 'reg_alpha': 1.659319209745088, 'reg_lambda': 8.695613725934824e-05}. Best is trial 37 with value: 3.0328952789306642.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run learned-stag-727 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/2c150730daa44da7ba3b6a1533273065
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:31:20,741] Trial 38 finished with value: 3.063031721115112 and parameters: {'n_estimators': 665, 'learning_rate': 0.022939872130669788, 'max_depth': 8, 'min_child_weight': 9, 'gamma': 0.3715325715751854, 'subsample': 0.7629998738232301, 'colsample_bytree': 0.8421303101131423, 'reg_alpha': 1.9835929558637797, 'reg_lambda': 8.904377727851027e-05}. Best is trial 37 with value: 3.0328952789306642.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run honorable-worm-178 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/664b2f52ce2a495e848013a95b36a9ec
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:31:32,728] Trial 39 finished with value: 3.2111883640289305 and parameters: {'n_estimators': 883, 'learning_rate': 0.024932845495376922, 'max_depth': 7, 'min_child_weight': 9, 'gamma': 1.184833550502573, 'subsample': 0.6010833516350524, 'colsample_bytree': 0.799254646637342, 'reg_alpha': 4.492802901064596, 'reg_lambda': 0.00025959581780948067}. Best is trial 37 with value: 3.0328952789306642.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run shivering-zebra-36 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/c4f604d5450c40819af252931a5394b5
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:31:52,475] Trial 40 finished with value: 3.297947359085083 and parameters: {'n_estimators': 790, 'learning_rate': 0.03362245649971003, 'max_depth': 4, 'min_child_weight': 6, 'gamma': 0.700912111017274, 'subsample': 0.7298365725410603, 'colsample_bytree': 0.8900578638190659, 'reg_alpha': 0.3914063731010107, 'reg_lambda': 2.912531209722911e-05}. Best is trial 37 with value: 3.0328952789306642.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run unique-squirrel-211 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/2b01048d530641c6820429dc6a7e196b
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:32:09,560] Trial 41 finished with value: 3.047496509552002 and parameters: {'n_estimators': 720, 'learning_rate': 0.013943116780134197, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 0.027410896259475626, 'subsample': 0.8063990607178118, 'colsample_bytree': 0.8624562687220757, 'reg_alpha': 0.9775243225327691, 'reg_lambda': 2.1259409003877042e-05}. Best is trial 37 with value: 3.0328952789306642.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run adorable-swan-589 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/14275c024c194cf1ac7395b3018ce725
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:32:28,477] Trial 42 finished with value: 3.0318999767303465 and parameters: {'n_estimators': 1139, 'learning_rate': 0.016450189045433657, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.3147752744616105, 'subsample': 0.7456720964676367, 'colsample_bytree': 0.8271082122295553, 'reg_alpha': 1.3679710218210603, 'reg_lambda': 5.81565703962658e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fortunate-dove-173 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/5d523e8a46354c00ba2b1a865b50f96f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:32:43,963] Trial 43 finished with value: 3.0415510177612304 and parameters: {'n_estimators': 1139, 'learning_rate': 0.016684537769299273, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.3917206188552349, 'subsample': 0.6844361287485864, 'colsample_bytree': 0.8326414384381713, 'reg_alpha': 3.3288241192744787, 'reg_lambda': 0.00017753914295969833}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run enthused-yak-82 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/d76ab088b0cc4fe1961300ae07f93fd6
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:32:50,857] Trial 44 finished with value: 3.1013689994812013 and parameters: {'n_estimators': 852, 'learning_rate': 0.026108149623077715, 'max_depth': 8, 'min_child_weight': 8, 'gamma': 0.9399900693996583, 'subsample': 0.7148567103822249, 'colsample_bytree': 0.803336096511663, 'reg_alpha': 1.7066828377428331, 'reg_lambda': 0.0006621469320155224}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run adorable-hound-186 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/8bf5127e1ef44ea287f5099720c84411
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:32:59,966] Trial 45 finished with value: 3.0375595092773438 and parameters: {'n_estimators': 455, 'learning_rate': 0.02269103407555648, 'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.6642376834639432, 'subsample': 0.7467417264872381, 'colsample_bytree': 0.8570409431790456, 'reg_alpha': 0.4060703577874626, 'reg_lambda': 6.25557320404356e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run defiant-seal-827 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/0cf17846dcc24e7caf5f43185e94f21d
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:33:20,000] Trial 46 finished with value: 3.0435577869415282 and parameters: {'n_estimators': 414, 'learning_rate': 0.0607401048808453, 'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.705322267900512, 'subsample': 0.7464623776355029, 'colsample_bytree': 0.8549193988746405, 'reg_alpha': 0.3590495862485217, 'reg_lambda': 8.375645122351632e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run capable-croc-595 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/37551b98e8f147099e48836a2a73d52f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:33:39,980] Trial 47 finished with value: 3.0930674076080322 and parameters: {'n_estimators': 248, 'learning_rate': 0.1374674252270679, 'max_depth': 11, 'min_child_weight': 10, 'gamma': 0.5830232591409187, 'subsample': 0.7791132025371023, 'colsample_bytree': 0.8355014111000707, 'reg_alpha': 0.05904259819990754, 'reg_lambda': 5.166987559293654e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run shivering-bear-123 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/4ea9afe4b3f54697838d28ae5fec3ed1
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:33:51,998] Trial 48 finished with value: 3.096141529083252 and parameters: {'n_estimators': 523, 'learning_rate': 0.028042435776330477, 'max_depth': 11, 'min_child_weight': 9, 'gamma': 1.249028173344021, 'subsample': 0.7571331301492795, 'colsample_bytree': 0.9172234535055532, 'reg_alpha': 5.8538882539065344, 'reg_lambda': 0.00018328517992519897}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bouncy-mink-110 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/34d08f5ce5c743ec8a36783713b979c5
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:34:08,040] Trial 49 finished with value: 3.0530731201171877 and parameters: {'n_estimators': 462, 'learning_rate': 0.022775636310196454, 'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.8860832512622859, 'subsample': 0.7356019454441235, 'colsample_bytree': 0.8034002517081142, 'reg_alpha': 0.5614877156398769, 'reg_lambda': 0.0006467237727862433}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run selective-robin-435 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/75ce884f15684c3ab1d3cf56b9d9b253
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:34:28,001] Trial 50 finished with value: 3.0506649017333984 and parameters: {'n_estimators': 589, 'learning_rate': 0.03564297102685981, 'max_depth': 12, 'min_child_weight': 10, 'gamma': 0.3093091176237125, 'subsample': 0.6456837944783226, 'colsample_bytree': 0.7717078130507394, 'reg_alpha': 2.480677264460051, 'reg_lambda': 1.9713409530897813e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fun-pig-918 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/1812058b03014d55a8f31bbd7fbf521b
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:34:52,009] Trial 51 finished with value: 3.042748546600342 and parameters: {'n_estimators': 1078, 'learning_rate': 0.01824695241458566, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.36510318611579085, 'subsample': 0.7201396588448011, 'colsample_bytree': 0.8939836231564795, 'reg_alpha': 1.3820208303418586, 'reg_lambda': 4.0863614854286624e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run overjoyed-steed-845 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/bcd568ffcf7b47819bd713d13cea6deb
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:35:08,014] Trial 52 finished with value: 3.0417829513549806 and parameters: {'n_estimators': 760, 'learning_rate': 0.016788623289654556, 'max_depth': 9, 'min_child_weight': 9, 'gamma': 0.25996360422161496, 'subsample': 0.7477502068254538, 'colsample_bytree': 0.8701829122103818, 'reg_alpha': 0.10800926687670456, 'reg_lambda': 0.00011202121454359775}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run receptive-mole-223 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/17946353f094409489ef0348996245bc
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:35:24,663] Trial 53 finished with value: 3.048563003540039 and parameters: {'n_estimators': 341, 'learning_rate': 0.014508205115382873, 'max_depth': 10, 'min_child_weight': 7, 'gamma': 0.640626188766417, 'subsample': 0.7734172585594351, 'colsample_bytree': 0.8279847283138047, 'reg_alpha': 0.5622236618023668, 'reg_lambda': 1.824803612185577e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run languid-shrew-617 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e58c877af3624a7da9f07bd510eaab28
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:35:36,056] Trial 54 finished with value: 3.0441659927368163 and parameters: {'n_estimators': 1152, 'learning_rate': 0.020570536430536506, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.9713016126998042, 'subsample': 0.7943387309621985, 'colsample_bytree': 0.9173476362783792, 'reg_alpha': 0.3005339071558933, 'reg_lambda': 6.593995566699448e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bedecked-steed-278 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/ecf35080fac64448b3c62b69da2d0b11
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:35:57,867] Trial 55 finished with value: 3.185263824462891 and parameters: {'n_estimators': 998, 'learning_rate': 0.10063253748898505, 'max_depth': 9, 'min_child_weight': 10, 'gamma': 0.004114611759345577, 'subsample': 0.6885733445614455, 'colsample_bytree': 0.8484894852205724, 'reg_alpha': 4.02201888454895, 'reg_lambda': 2.5983312069278515e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run debonair-turtle-412 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/eab97b20815e4250a1b632e7f4b40ed1
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:36:06,769] Trial 56 finished with value: 3.136506462097168 and parameters: {'n_estimators': 956, 'learning_rate': 0.011238490432344586, 'max_depth': 8, 'min_child_weight': 9, 'gamma': 1.3207294654498376, 'subsample': 0.6752641036843694, 'colsample_bytree': 0.7506851340735534, 'reg_alpha': 0.14548570291231355, 'reg_lambda': 0.0001405729414084224}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run unique-mare-576 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/45b7186afde24d8d8e8786f2b6cbb991
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:36:16,675] Trial 57 finished with value: 3.047143983840942 and parameters: {'n_estimators': 1045, 'learning_rate': 0.01858601014395115, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.5282266840049364, 'subsample': 0.7477080948316592, 'colsample_bytree': 0.7895832361789215, 'reg_alpha': 0.8079315911080441, 'reg_lambda': 0.0002748122922045446}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run honorable-snake-245 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3c571ac6416e4af2b578f3bf132f7612
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:36:29,212] Trial 58 finished with value: 3.044010353088379 and parameters: {'n_estimators': 1160, 'learning_rate': 0.030470828015063796, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.20386221759845852, 'subsample': 0.7032058638642709, 'colsample_bytree': 0.8805193738684427, 'reg_alpha': 1.6362015513039767, 'reg_lambda': 3.644650005679429e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fun-mink-358 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/23641f8582714d05879338246896b797
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:36:39,107] Trial 59 finished with value: 3.031992244720459 and parameters: {'n_estimators': 901, 'learning_rate': 0.013697384772375277, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.8590818057159664, 'subsample': 0.8223907548598343, 'colsample_bytree': 0.9034170979175431, 'reg_alpha': 0.23547788569094305, 'reg_lambda': 1.4969630753220557e-05}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run nosy-shark-645 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/26b8228dab1c4c209cc8f5450cc97442
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:36:53,046] Trial 60 finished with value: 3.060118007659912 and parameters: {'n_estimators': 663, 'learning_rate': 0.23236780145825398, 'max_depth': 12, 'min_child_weight': 1, 'gamma': 1.728550256130354, 'subsample': 0.8308826041530499, 'colsample_bytree': 0.9690171324318362, 'reg_alpha': 0.039708819794837376, 'reg_lambda': 0.00043177431144507644}. Best is trial 42 with value: 3.0318999767303465.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fortunate-colt-748 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/bd0444d08f0c4cec8d1c83d94d4bc74d
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:37:09,106] Trial 61 finished with value: 3.0310139656066895 and parameters: {'n_estimators': 1089, 'learning_rate': 0.013475250803191008, 'max_depth': 11, 'min_child_weight': 7, 'gamma': 0.8155134116591854, 'subsample': 0.7911683759249725, 'colsample_bytree': 0.8991201763749328, 'reg_alpha': 0.2492789166122371, 'reg_lambda': 2.030731519337233e-05}. Best is trial 61 with value: 3.0310139656066895.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run unique-donkey-352 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/fd8a607de3c849e0a0167abadeb3d97a
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:37:24,662] Trial 62 finished with value: 3.0304047584533693 and parameters: {'n_estimators': 1086, 'learning_rate': 0.010782548413964827, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.7980305601770312, 'subsample': 0.8532359308185443, 'colsample_bytree': 0.901288414945554, 'reg_alpha': 0.32006077643199066, 'reg_lambda': 1.79616491393364e-05}. Best is trial 62 with value: 3.0304047584533693.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run welcoming-dove-164 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/a7eede4b5f72425ba11713e4685728d5
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:37:35,600] Trial 63 finished with value: 3.047740411758423 and parameters: {'n_estimators': 1087, 'learning_rate': 0.010724175158194285, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 1.3779050740540524, 'subsample': 0.8564785367931165, 'colsample_bytree': 0.8984396273227574, 'reg_alpha': 0.023189366895011145, 'reg_lambda': 4.415534741319809e-05}. Best is trial 62 with value: 3.0304047584533693.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bald-gnat-580 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/4484aaa9aa94456782efd0ed497a239a
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:37:48,529] Trial 64 finished with value: 3.031339979171753 and parameters: {'n_estimators': 899, 'learning_rate': 0.01661907623217352, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.7655029026195055, 'subsample': 0.8723102700106287, 'colsample_bytree': 0.9082320336204561, 'reg_alpha': 0.2397259205447976, 'reg_lambda': 8.001595534766164e-05}. Best is trial 62 with value: 3.0304047584533693.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run dapper-tern-344 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/7f9970b1ff7848bca9d050e1507ddeab
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:38:04,550] Trial 65 finished with value: 3.066778039932251 and parameters: {'n_estimators': 888, 'learning_rate': 0.29866373378393163, 'max_depth': 11, 'min_child_weight': 7, 'gamma': 1.0045976810330859, 'subsample': 0.8676324754304959, 'colsample_bytree': 0.9300557519800312, 'reg_alpha': 0.11188004092187966, 'reg_lambda': 1.5708561905514617e-05}. Best is trial 62 with value: 3.0304047584533693.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run industrious-doe-880 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/9c704c5ea2f9461c89946ad36d815781
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:38:17,751] Trial 66 finished with value: 3.028222179412842 and parameters: {'n_estimators': 838, 'learning_rate': 0.015974063741255047, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.8206204766603393, 'subsample': 0.8472932643036117, 'colsample_bytree': 0.961085145360132, 'reg_alpha': 0.2340307272315332, 'reg_lambda': 9.216959967237322e-05}. Best is trial 66 with value: 3.028222179412842.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fearless-hound-56 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/d2fdf41dd305435d9140bb819c0c078d
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:38:28,626] Trial 67 finished with value: 3.026572322845459 and parameters: {'n_estimators': 858, 'learning_rate': 0.017278710793843292, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.8079845632069346, 'subsample': 0.8790811784699684, 'colsample_bytree': 0.989874578940999, 'reg_alpha': 0.19433375109850667, 'reg_lambda': 9.173999991845001e-05}. Best is trial 67 with value: 3.026572322845459.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run thundering-fowl-938 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e36b3f7ee9ac4d33b5279af76db9838f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:38:41,238] Trial 68 finished with value: 3.027837133407593 and parameters: {'n_estimators': 817, 'learning_rate': 0.016417145182070613, 'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.8201837219569312, 'subsample': 0.8842703669128185, 'colsample_bytree': 0.9938316331089104, 'reg_alpha': 0.22688945553339238, 'reg_lambda': 0.00022009406389257593}. Best is trial 67 with value: 3.026572322845459.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run angry-moose-343 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3d7b286650d1437cad308767284cf470
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:39:00,550] Trial 69 finished with value: 3.0277196407318114 and parameters: {'n_estimators': 829, 'learning_rate': 0.016037253200091358, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.0698889343152076, 'subsample': 0.9187371907712949, 'colsample_bytree': 0.9929206507753109, 'reg_alpha': 0.07520212451417607, 'reg_lambda': 0.00021932699371390223}. Best is trial 67 with value: 3.026572322845459.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run unleashed-smelt-716 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/0ead3401eb0b4c01aad5461eb1bcce39
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:39:16,548] Trial 70 finished with value: 3.025420808792114 and parameters: {'n_estimators': 834, 'learning_rate': 0.010004078539318182, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.0663887710206568, 'subsample': 0.9255313757658576, 'colsample_bytree': 0.9984149368390314, 'reg_alpha': 0.06532952532935969, 'reg_lambda': 0.000849458589898967}. Best is trial 70 with value: 3.025420808792114.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run judicious-wasp-817 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/7ca53d3ba2e84d748c961768dd8faeb1
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:39:33,103] Trial 71 finished with value: 3.026863861083984 and parameters: {'n_estimators': 816, 'learning_rate': 0.010400130680899143, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.094036840715426, 'subsample': 0.9175945089007294, 'colsample_bytree': 0.9995712347894825, 'reg_alpha': 0.0656799792414341, 'reg_lambda': 0.0009254805697096597}. Best is trial 70 with value: 3.025420808792114.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run bouncy-roo-289 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e05cd6453d654a8894b95b7264b81baf
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:39:47,683] Trial 72 finished with value: 3.0252688407897947 and parameters: {'n_estimators': 759, 'learning_rate': 0.01000114930352783, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 1.060499240899745, 'subsample': 0.923036323097711, 'colsample_bytree': 0.9993616700907297, 'reg_alpha': 0.07627562546022172, 'reg_lambda': 0.00290926999065413}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run brawny-bass-3 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/129c17e4597645ee82b3def02a02ebb0
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:39:59,726] Trial 73 finished with value: 3.0260520935058595 and parameters: {'n_estimators': 824, 'learning_rate': 0.010104704750643729, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.0736059534936997, 'subsample': 0.9246442608426833, 'colsample_bytree': 0.9973744626757753, 'reg_alpha': 0.02627690738494133, 'reg_lambda': 0.006893531332133509}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run fun-bird-62 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/c59b18681e374090830fe8d86b72aaee
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:40:10,167] Trial 74 finished with value: 3.041900873184204 and parameters: {'n_estimators': 817, 'learning_rate': 0.010059404970934412, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.6429132887843574, 'subsample': 0.9260266329096037, 'colsample_bytree': 0.9972806536797414, 'reg_alpha': 0.02166395567549403, 'reg_lambda': 0.005214742373582025}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run delicate-bat-231 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/d3f1ea5851414758819cd7c706b70b91
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:40:28,597] Trial 75 finished with value: 3.0273102283477784 and parameters: {'n_estimators': 762, 'learning_rate': 0.012102278349466969, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 1.0922387430572642, 'subsample': 0.9757767901104674, 'colsample_bytree': 0.9825717456151641, 'reg_alpha': 0.01145631799109226, 'reg_lambda': 0.012249073621682434}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run painted-eel-630 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/b32c16c65423429daf8153ca18091038
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:40:45,386] Trial 76 finished with value: 3.0370942115783692 and parameters: {'n_estimators': 760, 'learning_rate': 0.011642782077771167, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 1.446613532142773, 'subsample': 0.9591953023304687, 'colsample_bytree': 0.9828920110577603, 'reg_alpha': 0.0032753597420887713, 'reg_lambda': 0.010285652062907517}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run trusting-calf-755 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/2618675d27a04922a8c74fe62c7ce069
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:41:04,609] Trial 77 finished with value: 3.0514281749725343 and parameters: {'n_estimators': 781, 'learning_rate': 0.012281876588416734, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 1.9061935288604475, 'subsample': 0.9175793173788807, 'colsample_bytree': 0.9830416070311958, 'reg_alpha': 0.011773151821615143, 'reg_lambda': 0.00324755953789785}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run trusting-moth-603 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/c69276e449b74a06a5804c69c1419e00
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:41:15,697] Trial 78 finished with value: 3.028933954238892 and parameters: {'n_estimators': 756, 'learning_rate': 0.010105666448939577, 'max_depth': 12, 'min_child_weight': 6, 'gamma': 1.0927848599417742, 'subsample': 0.8887378647814249, 'colsample_bytree': 0.9998854701733007, 'reg_alpha': 0.0681040695980602, 'reg_lambda': 0.027398627662788895}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run silent-mare-475 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/328ccc37c1094f3a9e4a98ce1f992fcc
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:41:26,110] Trial 79 finished with value: 3.032118892669678 and parameters: {'n_estimators': 723, 'learning_rate': 0.011301101363535793, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 1.2674217628124596, 'subsample': 0.9822103718320488, 'colsample_bytree': 0.970337094064116, 'reg_alpha': 0.014242253419284465, 'reg_lambda': 0.0022737650910934484}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run nervous-dove-701 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/906a1f3b2cc34fe488c44720c648c20e
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:41:37,715] Trial 80 finished with value: 3.0279830932617187 and parameters: {'n_estimators': 689, 'learning_rate': 0.014882741230926685, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.0827425028612854, 'subsample': 0.9519190734589629, 'colsample_bytree': 0.9888939860959748, 'reg_alpha': 0.0059906021349451595, 'reg_lambda': 0.0009425126545548271}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run thundering-moose-972 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/f73b4ad227d844d0804d84978cd8b392
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:41:53,148] Trial 81 finished with value: 3.040436363220215 and parameters: {'n_estimators': 687, 'learning_rate': 0.01276052655391547, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.54915398822406, 'subsample': 0.950812971163959, 'colsample_bytree': 0.9878293558841579, 'reg_alpha': 0.0047116400540016656, 'reg_lambda': 0.0012738441388579524}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run exultant-squid-319 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e5d1c367f2ab42a09f8a5a8aa9c1910f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:42:05,741] Trial 82 finished with value: 3.033105230331421 and parameters: {'n_estimators': 866, 'learning_rate': 0.014946577954598476, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.0594388901043468, 'subsample': 0.9790718798503557, 'colsample_bytree': 0.9509401769304634, 'reg_alpha': 0.0011023251734968282, 'reg_lambda': 0.0008252498149216854}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run gifted-sloth-600 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/14c7b9151baf4ccc96c82b87d5497d9f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:42:20,650] Trial 83 finished with value: 3.0356029987335207 and parameters: {'n_estimators': 815, 'learning_rate': 0.01187381217798039, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.3693958249780653, 'subsample': 0.9153910235912187, 'colsample_bytree': 0.9719250702129197, 'reg_alpha': 0.04798665645411459, 'reg_lambda': 0.010257729710076479}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run wistful-seal-34 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/41a1cfeae04f4295a0aa7e9e30addf6d
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:42:29,169] Trial 84 finished with value: 3.0320483207702638 and parameters: {'n_estimators': 609, 'learning_rate': 0.020193451930259176, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.1985242634799742, 'subsample': 0.8885114230475691, 'colsample_bytree': 0.990544911879223, 'reg_alpha': 0.03179311262121356, 'reg_lambda': 0.002517992860439502}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run clumsy-whale-679 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/cbdbf47c1f784a8ab1c316f2a7c674b7
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:42:40,206] Trial 85 finished with value: 3.031319189071655 and parameters: {'n_estimators': 736, 'learning_rate': 0.014761083465833005, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.0594596818883475, 'subsample': 0.9369850097850134, 'colsample_bytree': 0.9576932840497988, 'reg_alpha': 0.006214225416510725, 'reg_lambda': 0.0010320904520776284}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run flawless-worm-231 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/55b4eae78d554d82b4b0e183eb41541f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:42:56,628] Trial 86 finished with value: 3.123225545883179 and parameters: {'n_estimators': 799, 'learning_rate': 0.010738604848260917, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 4.712143622575618, 'subsample': 0.9681637119928479, 'colsample_bytree': 0.9784909908516455, 'reg_alpha': 0.08809176145351987, 'reg_lambda': 0.0064505906203150744}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run spiffy-wren-148 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/561ea6793a9949fea621b17e85e78f30
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:43:12,653] Trial 87 finished with value: 3.030088710784912 and parameters: {'n_estimators': 692, 'learning_rate': 0.012478203361949743, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.1697249354816657, 'subsample': 0.9491633685602497, 'colsample_bytree': 0.9763911476229544, 'reg_alpha': 0.029678601022293326, 'reg_lambda': 0.01941776576202464}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run peaceful-flea-154 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/228bd51445bb4f108b32e13392ffa01e
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:43:32,670] Trial 88 finished with value: 3.02645583152771 and parameters: {'n_estimators': 857, 'learning_rate': 0.017965958185183633, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.0080030875574628, 'subsample': 0.9262165296346001, 'colsample_bytree': 0.9916723360827031, 'reg_alpha': 0.017094364464265543, 'reg_lambda': 0.0005264234663136248}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run nimble-ox-485 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/7b4b35e1c80a4c75b9b440327f46c986
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:43:45,218] Trial 89 finished with value: 3.031319522857666 and parameters: {'n_estimators': 843, 'learning_rate': 0.017664281974312943, 'max_depth': 11, 'min_child_weight': 7, 'gamma': 0.9475068332544698, 'subsample': 0.9107229701514873, 'colsample_bytree': 0.9450476050952582, 'reg_alpha': 0.01573690735010177, 'reg_lambda': 0.00207474129052851}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run intelligent-swan-863 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/f672f527afc44fdb8817736a1669c2cc
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:43:58,815] Trial 90 finished with value: 3.0367403984069825 and parameters: {'n_estimators': 869, 'learning_rate': 0.01096948556108196, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 1.4422760055066282, 'subsample': 0.9239282113508441, 'colsample_bytree': 0.9613269664764117, 'reg_alpha': 0.05679331967417579, 'reg_lambda': 0.0004661143283406578}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run upset-ram-588 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/e4cb3862b67741fba91fbf52226a5624
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:44:12,687] Trial 91 finished with value: 3.035371494293213 and parameters: {'n_estimators': 774, 'learning_rate': 0.018754523735672407, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.2754872126210801, 'subsample': 0.9995990736729392, 'colsample_bytree': 0.999445698633336, 'reg_alpha': 0.13938518510889406, 'reg_lambda': 0.00021189200320196895}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run glamorous-sloth-215 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/fefdb069fd1740d6973b34dc6373749b
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:44:22,698] Trial 92 finished with value: 3.027149200439453 and parameters: {'n_estimators': 804, 'learning_rate': 0.014137554543704895, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.035733989895796, 'subsample': 0.901493875733025, 'colsample_bytree': 0.9899098673774716, 'reg_alpha': 0.0015225295252091723, 'reg_lambda': 0.0006631566510742427}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run caring-chimp-322 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/fafe0864ed0a4796865ca8a3aa6e1603
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:44:32,219] Trial 93 finished with value: 3.027476739883423 and parameters: {'n_estimators': 827, 'learning_rate': 0.021250703756111145, 'max_depth': 12, 'min_child_weight': 8, 'gamma': 0.9539126154724471, 'subsample': 0.8920263270249915, 'colsample_bytree': 0.9669183581209951, 'reg_alpha': 0.00017503154013569306, 'reg_lambda': 0.0036137436284555367}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run gaudy-newt-16 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/2edabc6ca33647149671e7ae81ca9560
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:44:46,786] Trial 94 finished with value: 3.0267555713653564 and parameters: {'n_estimators': 924, 'learning_rate': 0.013118245519323269, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 0.9482395208653931, 'subsample': 0.8992289968753753, 'colsample_bytree': 0.965850840710369, 'reg_alpha': 0.00010131536483610847, 'reg_lambda': 0.00445932222656641}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run angry-frog-414 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/3a2be71466474c9ebd30b8513d81edbc
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:45:04,699] Trial 95 finished with value: 3.028159189224243 and parameters: {'n_estimators': 929, 'learning_rate': 0.02137193054405552, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 0.9720223596435719, 'subsample': 0.8973029825715116, 'colsample_bytree': 0.9652388080571039, 'reg_alpha': 6.738448680652809e-05, 'reg_lambda': 0.0040888299916000785}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run rumbling-sponge-411 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/f3b72ba8cf1c4619932101fb5f18b86f
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:45:17,494] Trial 96 finished with value: 3.057041788101196 and parameters: {'n_estimators': 799, 'learning_rate': 0.013055020224327174, 'max_depth': 12, 'min_child_weight': 9, 'gamma': 1.9806033224373878, 'subsample': 0.9294885340979612, 'colsample_bytree': 0.9533010119664529, 'reg_alpha': 8.552453527783547e-05, 'reg_lambda': 0.010034033256198616}. Best is trial 72 with value: 3.0252688407897947.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run valuable-bat-659 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/f02f877b32ba431e823fe18f566bc59c
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:45:32,826] Trial 97 finished with value: 3.023421049118042 and parameters: {'n_estimators': 856, 'learning_rate': 0.011804738897525, 'max_depth': 12, 'min_child_weight': 6, 'gamma': 0.6035875191188472, 'subsample': 0.9028989534142778, 'colsample_bytree': 0.9791480707107688, 'reg_alpha': 0.00020972186331087944, 'reg_lambda': 0.0033654731421510226}. Best is trial 97 with value: 3.023421049118042.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run dazzling-moth-181 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/ed4f4e1b352a493bacf2c9a5637708d5
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:45:50,011] Trial 98 finished with value: 3.0242630004882813 and parameters: {'n_estimators': 876, 'learning_rate': 0.010083080300631106, 'max_depth': 11, 'min_child_weight': 6, 'gamma': 0.5113753636039032, 'subsample': 0.9411287021126775, 'colsample_bytree': 0.9819661262405106, 'reg_alpha': 1.272561662934443e-05, 'reg_lambda': 0.0015304635916392488}. Best is trial 97 with value: 3.023421049118042.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

🏃 View run secretive-koi-997 at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/d6facf1636bc4c3785e233301af57011
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3
[I 2026-07-18 19:46:04,725] Trial 99 finished with value: 3.35311222076416 and parameters: {'n_estimators': 954, 'learning_rate': 0.01067006018460292, 'max_depth': 4, 'min_child_weight': 5, 'gamma': 0.4945417796810887, 'subsample': 0.9072338012075106, 'colsample_bytree': 0.9370345103698375, 'reg_alpha': 1.130459826091688e-05, 'reg_lambda': 0.0016642727278612995}. Best is trial 97 with value: 3.023421049118042.
🏃 View run XGBoost Hyperparameter Tuning at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3/runs/f4f2df0159db4b58aa70dbd7231dad90
🧪 View experiment at: https://dagshub.com/xlrboi/delievery_time_prediction.mlflow/#/experiments/3

In [36]:
best_xgb = XGBRegressor(
        **study.best_params,
        random_state=42,
        device="cuda",
        tree_method="hist",
        objective="reg:squarederror",
        eval_metric="mae",
        verbosity=0
    )
final_model = TransformedTargetRegressor(
        regressor=best_xgb,
        transformer=pt
    )

final_model.fit(X_train_trans, y_train)

y_pred_train = final_model.predict(X_train_trans)
y_pred_test = final_model.predict(X_test_trans)

scores = cross_validate(
        estimator=final_model,
        X=X_train_trans,
        y=y_train,
        cv=5,
        scoring="neg_mean_absolute_error",
        return_train_score=True,
        n_jobs=1
    )

mlflow.log_metric("train_mae", mean_absolute_error(y_train, y_pred_train))
mlflow.log_metric("test_mae", mean_absolute_error(y_test, y_pred_test))
mlflow.log_metric("train_r2", r2_score(y_train, y_pred_train))
mlflow.log_metric("test_r2", r2_score(y_test, y_pred_test))
mlflow.log_metric("final_cv_mae", -scores["test_score"].mean())

mlflow.sklearn.log_model(final_model, name="model",skops_trusted_types=[
        "xgboost.core.Booster",
        "xgboost.sklearn.XGBRegressor",
    ],)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

In [40]:
study.best_params

{'n_estimators': 856,
 'learning_rate': 0.011804738897525,
 'max_depth': 12,
 'min_child_weight': 6,
 'gamma': 0.6035875191188472,
 'subsample': 0.9028989534142778,
 'colsample_bytree': 0.9791480707107688,
 'reg_alpha': 0.00020972186331087944,
 'reg_lambda': 0.0033654731421510226}

In [41]:
study.best_value

3.023421049118042

In [37]:
optuna.visualization.plot_optimization_history(study)

In [38]:
optuna.visualization.plot_param_importances(study)

In [39]:
optuna.visualization.plot_slice(study)